package com.diplom.work;

import java.sql.Connection;
import java.sql.PreparedStatement;
import com.mysql.jdbc.*;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.year;
import java.awt.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.basic.BasicLookAndFeel;
import javax.swing.table.DefaultTableModel;

public class MainView extends javax.swing.JFrame {

    public MainView() {
        initComponents();
        setSize(1600, 850);
        setResizable(false);
        tableUpdate();
        setPreferredSize(new Dimension(1600, 850));
        ViewDate viewDate = new ViewDate();
        lblDate.setText(viewDate.year + "/" + (viewDate.month + 1) + "/" + viewDate.day);
        
    }
    SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPart = new javax.swing.JTextField();
        txtPlane = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPartModel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPlaneModel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        radioButtonNo = new javax.swing.JRadioButton();
        radioButtonYes = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtSpareType = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSerialNo = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        radioBtnServiceable = new javax.swing.JRadioButton();
        radioBtnNotServiceable = new javax.swing.JRadioButton();
        dateChooser = new org.netbeans.modules.form.InvalidComponent();
        btnClear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\t\t\tAircraft Spare Parts Management");
        setBackground(new java.awt.Color(51, 182, 246));
        setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        setForeground(new java.awt.Color(185, 225, 255));
        setIconImages(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Spare Name", "Part No", "Aircraft", "Aircraft Type", "IsNew", "OrderDate", "Country", "Spare Type", "Serial No", "Spare Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 458, 1489, 329));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24), java.awt.Color.magenta)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Spare Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Aircraft");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Date");

        txtPart.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtPlane.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Spare Model");

        txtPartModel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Aircraft Type");

        txtPlaneModel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Country");

        txtCountry.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IS NEW?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 18), java.awt.Color.red)); // NOI18N

        buttonGroup1.add(radioButtonNo);
        radioButtonNo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        radioButtonNo.setText("No");
        radioButtonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonNoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioButtonYes);
        radioButtonYes.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        radioButtonYes.setText("Yes");
        radioButtonYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonYesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButtonNo)
                    .addComponent(radioButtonYes))
                .addGap(84, 84, 84))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioButtonYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(radioButtonNo))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Spare Type");

        txtSpareType.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Serial No");

        txtSerialNo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Spare Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 18), java.awt.Color.red)); // NOI18N

        buttonGroup2.add(radioBtnServiceable);
        radioBtnServiceable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        radioBtnServiceable.setText("Serviceable");

        buttonGroup2.add(radioBtnNotServiceable);
        radioBtnNotServiceable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        radioBtnNotServiceable.setText("Not-Serviceable");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioBtnServiceable)
                    .addComponent(radioBtnNotServiceable))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioBtnServiceable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioBtnNotServiceable))
        );

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Clear-icon.png"))); // NOI18N
        btnClear.setBorder(null);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPart, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPartModel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlane, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlaneModel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtSpareType)
                    .addComponent(txtCountry)
                    .addComponent(txtSerialNo)
                    .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPart, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPlaneModel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtPartModel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlane, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(txtSpareType, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClear))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 86, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Action Group", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        btnAdd.setBackground(java.awt.Color.pink);
        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/system-database-add-icon.png"))); // NOI18N
        btnAdd.setText("Əlavə et");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Very-Basic-Update-icon.png"))); // NOI18N
        btnUpdate.setText("Yenilə");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Button-Delete-icon.png"))); // NOI18N
        btnDelete.setText("Datanı Sil");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 51, 51));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Start-Menu-Search-icon-x32.png"))); // NOI18N
        btnSearch.setText("AXTAR");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1357, 86, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("AIRCRAFT SPARE PARTS MANAGEMENT SOFTWARE 2020");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 25, -1, -1));

        lblDate.setBackground(new java.awt.Color(204, 204, 255));
        lblDate.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblDate.setForeground(new java.awt.Color(51, 0, 255));
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 790, 130, 29));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableUpdate() {
        int column;
        try {

            Class.forName("com.mysql.jdbc.Driver");

            connection1 = DriverManager.getConnection(
                    "jdbc:mysql://localhost/spareparts?autoReconnect=true&useSSL=false", "root", "2020"
            );
            insert = connection1.prepareStatement(
                    "SELECT * FROM parts"
            );

            ResultSet resultSet = insert.executeQuery();
            ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
            column = resultSetMetaData.getColumnCount();

            DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();

            defaultTableModel.setRowCount(0);            

            while (resultSet.next()) {
                Vector vector = new Vector();
                for (int i = 1; i <= column; i++) {
                    vector.add(resultSet.getString("part_id"));
                    vector.add(resultSet.getString("SpareName"));
                    vector.add(resultSet.getString("PartNo"));
                    vector.add(resultSet.getString("Aircraft"));
                    vector.add(resultSet.getString("AircraftType"));
                    vector.add(resultSet.getString("IsNew"));
                    vector.add(resultSet.getString("OrderDate"));
                    vector.add(resultSet.getString("Country"));
                    vector.add(resultSet.getString("SpareType"));
                    vector.add(resultSet.getString("SerialNo"));
                    vector.add(resultSet.getString("SpareStatus"));
                }
                defaultTableModel.addRow(vector);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    Connection connection1;
    PreparedStatement insert;
    protected String is_New;


    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        btnAdd.setBackground(Color.pink);       
        String part = txtPart.getText();
        String partModel = txtPartModel.getText();
        String plane = txtPlane.getText();
        String planeModel = txtPlaneModel.getText();
        String date = simpleDateFormat.format(dateChooser.getDate());
        String country = txtCountry.getText();
        String spareType = txtSpareType.getText();
        String serialNo = txtSerialNo.getText();
        JRadioButton selectedButton = null;
        if (radioBtnServiceable.isSelected()) {
            selectedButton = radioBtnServiceable;
        } else if (radioBtnNotServiceable.isSelected()) {
            selectedButton = radioBtnNotServiceable;
        }
        String spareStatus = selectedButton.getText();
    
        try {
            
            Class.forName("com.mysql.jdbc.Driver");

            connection1 = DriverManager.getConnection(
                    "jdbc:mysql://localhost/spareparts?autoReconnect=true&useSSL=false", "root", "2020"
            );
            insert = connection1.prepareStatement("INSERT INTO parts (SpareName, PartNo, Aircraft, AircraftType, IsNew, OrderDate, Country, SpareType, SerialNo, SpareStatus) VALUES (?,?,?,?,?,?,?,?,?,?)");

            insert.setString(1, part);
            insert.setString(2, partModel);
            insert.setString(3, plane);
            insert.setString(4, planeModel);
            insert.setString(5, is_New);
            insert.setString(6, date);
            insert.setString(7, country);
            insert.setString(8, spareType);
            insert.setString(9, serialNo);
            insert.setString(10, spareStatus);
            
            insert.executeUpdate();

            JOptionPane.showMessageDialog(this, "Məlumat əlavə edildi.");
            tableUpdate();

            txtPart.setText("");
            txtPartModel.setText("");
            txtPlane.setText("");
            txtCountry.setText("");
            txtPlaneModel.setText("");
            simpleDateFormat.setCalendar(null);
            txtSpareType.setText("");
            txtSerialNo.setText("");

            txtPart.requestFocus();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void radioButtonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonNoActionPerformed
        is_New = "No";
    }//GEN-LAST:event_radioButtonNoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        ResultSet rs = null;
        int selectedIndex = jTable1.getSelectedRow();
        txtPart.setText(defaultTableModel.getValueAt(selectedIndex, 1).toString());
        txtPartModel.setText(defaultTableModel.getValueAt(selectedIndex, 2).toString());
        txtPlane.setText(defaultTableModel.getValueAt(selectedIndex, 3).toString());
        txtPlaneModel.setText(defaultTableModel.getValueAt(selectedIndex, 4).toString());
        txtCountry.setText(defaultTableModel.getValueAt(selectedIndex, 7).toString());
        txtSpareType.setText(defaultTableModel.getValueAt(selectedIndex, 8).toString());
        txtSerialNo.setText(defaultTableModel.getValueAt(selectedIndex, 9).toString());
        
        try {
            jTable1.getSelectedRow();
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)defaultTableModel.getValueAt(selectedIndex,6));
            dateChooser.setDate(date);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, e);
        }        
        

    }//GEN-LAST:event_jTable1MouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        try {
            int part_id = Integer.parseInt(defaultTableModel.getValueAt(selectedIndex, 0).toString());
            String part = txtPart.getText();
            String partModel = txtPartModel.getText();
            String plane = txtPlane.getText();
            String planeModel = txtPlaneModel.getText();
            String date = simpleDateFormat.format(dateChooser.getDate());
            String country = txtCountry.getText();
            String spareType = txtSpareType.getText();
            String serialNo = txtSerialNo.getText();

            JRadioButton selectedButton = null;
            if (radioBtnServiceable.isSelected()) {
                selectedButton = radioBtnServiceable;
            } else if (radioBtnNotServiceable.isSelected()) {
                selectedButton = radioBtnNotServiceable;
            }
            String choice = selectedButton.getText();
            String spareStatus = choice;

            Class.forName("com.mysql.jdbc.Driver");

            connection1 = DriverManager.getConnection(
                    "jdbc:mysql://localhost/spareparts?autoReconnect=true&useSSL=false", "root", "2020"
            );
            insert = connection1.prepareStatement(
                    "UPDATE parts set SpareName = ?, PartNo = ?, Aircraft = ?, AircraftType = ?, IsNew = ?, OrderDate = ?, Country = ?, SpareType = ?, SerialNo = ?, SpareStatus = ? WHERE part_id = ?"
            );

            insert.setString(1, part);
            insert.setString(2, partModel);
            insert.setString(3, plane);
            insert.setString(4, planeModel);
            insert.setString(5, is_New);
            insert.setString(6, date);
            insert.setString(7, country);
            insert.setString(8, spareType);
            insert.setString(9, serialNo);
            insert.setString(10, spareStatus);
            
            insert.setInt(11, part_id);
            insert.executeUpdate();

            JOptionPane.showMessageDialog(this, "Məlumat yeniləndi.");
            tableUpdate();

            txtPart.setText("");
            txtPartModel.setText("");
            txtPlane.setText("");
            txtCountry.setText("");
            txtPlaneModel.setText("");
            simpleDateFormat.setCalendar(null);
            txtSpareType.setText("");
            txtSerialNo.setText("");

            txtPart.requestFocus();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        try {
            int part_id = Integer.parseInt(defaultTableModel.getValueAt(selectedIndex, 0).toString());
            int dialogResult = JOptionPane.showConfirmDialog(
                    null,
                    "Məlumatı silmək istəyirsinizmi?",
                    "Warning", JOptionPane.YES_NO_OPTION
            );
            if (dialogResult == JOptionPane.YES_OPTION) {
                Class.forName("com.mysql.jdbc.Driver");

                connection1 = DriverManager.getConnection(
                        "jdbc:mysql://localhost/spareparts?autoReconnect=true&useSSL=false", "root", "2020"
                );
                insert = connection1.prepareStatement(
                        "DELETE FROM parts WHERE part_id = ?"
                );
                insert.setInt(1, part_id);
                insert.executeUpdate();
                JOptionPane.showMessageDialog(this, "Məlumat bazadan silindi.");
                tableUpdate();
                txtPart.setText("");
                txtPartModel.setText("");
                txtPlane.setText("");
                txtCountry.setText("");
                txtPlaneModel.setText("");
                simpleDateFormat.setCalendar(null);
                txtSpareType.setText("");
                txtSerialNo.setText("");
                
                txtPart.requestFocus();
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        SearchView searchView = new SearchView();
        searchView.setVisible(true);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void radioButtonYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonYesActionPerformed
        is_New = "Yes";
    }//GEN-LAST:event_radioButtonYesActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
        txtPart.setText("");
        txtPartModel.setText("");
        txtPlane.setText("");
        txtPlaneModel.setText("");
        txtCountry.setText("");
        txtSerialNo.setText("");
        txtSpareType.setText("");        
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        ResultSet rs = null;
        int selectedIndex = jTable1.getSelectedRow();
        try {
            jTable1.getSelectedRow();
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)defaultTableModel.getValueAt(selectedIndex,6));
            dateChooser.setDate(null);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnClearActionPerformed

    public static void main(String args[]) {
        
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException | ClassNotFoundException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }

        //"com.sun.java.swing.plaf.windows.WindowsLookAndFeel"
        //"com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel"

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private org.netbeans.modules.form.InvalidComponent dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JRadioButton radioBtnNotServiceable;
    private javax.swing.JRadioButton radioBtnServiceable;
    private javax.swing.JRadioButton radioButtonNo;
    private javax.swing.JRadioButton radioButtonYes;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtPart;
    private javax.swing.JTextField txtPartModel;
    private javax.swing.JTextField txtPlane;
    private javax.swing.JTextField txtPlaneModel;
    private javax.swing.JTextField txtSerialNo;
    private javax.swing.JTextField txtSpareType;
    // End of variables declaration//GEN-END:variables
}
